unit legends;
interface 
    uses crt;
    procedure legends_run;
implementation
    procedure legends_run;
    begin
writeln('Legends:');
writeln('A. J. Venter');
writeln('Алексей Лагунов');
writeln('Alexander Grau');
writeln('Alexander S. Klenin');
writeln('Alexander Shiyan');
writeln('Alexandr Gridnev');
writeln('Alexandre Leclerc');
writeln('Alexandru Alexandrov');
writeln('Alexey Torgashin');
writeln('Andreas Hausladen');
writeln('Andreas Schneider');
writeln('Andrew Haines');
writeln('Andrew Johnson');
writeln('Andrey Zubarev');
writeln('Anton A. Panferov');
writeln('Anton Kavalenka');
writeln('Antônio Galvão');
writeln('Arnold Bosch');
writeln('Attila Tamás - Hungarian translation');
writeln('August Klein');
writeln('Babak Mahmoudabadi');
writeln('Balazs Szekely');
writeln('Bald Zhang');
writeln('Bart Broersma');
writeln('Benito van der Zander');
writeln('Bent Normann Olsen');
writeln('Bernd Engelhardt');
writeln('Bernd Kreuss');
writeln('Bernd Mueller');
writeln('Bob Wingard');
writeln('Bogusław Brandys');
writeln('Boian Mitov');
writeln('Boris Arko');
writeln('Boris Glavin');
writeln('Boris Popov');
writeln('Brad Campbell');
writeln('Bruce Tulloch');
writeln('Chris Rorden');
writeln('Christian Budde');
writeln('Christian Iversen');
writeln('Christian Ulrich');
writeln('Christo Crause');
writeln('Christopher Kirkpatrick');
writeln('Cliff Baeseman');
writeln('Colin Western');
writeln('Curtis White');
writeln('Daniel Oom');
writeln('Daniel Simões de Almeida');
writeln('Darek Mazur');
writeln('Darius Blaszijk');
writeln('Dávid Fehér - Hungarian translation');
writeln('David Guadagnini');
writeln('David Jenkins');
writeln('David Pethes');
writeln('David Zimmer');
writeln('Dean Zobec');
writeln('Denis Golovan');
writeln('Denis Kozlov');
writeln('Denis Volodarsky');
writeln('Derit Agustin');
writeln('Dimitrios Chr. Ioannidis');
writeln('Diogo Piçarra');
writeln('Dirk Schiphorst');
writeln('Dmitry Boyarintsev');
writeln('Dominique Louis');
writeln('Don Siders');
writeln('Ere Maijala');
writeln('Eric Chapman');
writeln('Erivelton Silva');
writeln('Erwin van den Bosch');
writeln('Eugene Kryukov');
writeln('Evgen A. Palamarchuck');
writeln('Ezik Shlomi');
writeln('Fabrizio Fellini');
writeln('Fathony Luthfillah (x2nie)');
writeln('Felipe Monteiro de Carvalho');
writeln('Flávio Etrusco');
writeln('Florian Koeberle');
writeln('Francisco Manuel');
writeln('Gabor Boros');
writeln('Gerard Visent');
writeln('Gilles Vasseur - French translation');
writeln('Giuliano Colla');
writeln('Giulio Bernardi');
writeln('GongYu');
writeln('Graeme Geldenhuys');
writeln('Grzegorz Zakrzewski');
writeln('Gustavo Carreno');
writeln('Hakan Kizilhan');
writeln('Hans Luijten');
writeln('Hans-Joachim Ott');
writeln('Hans-Peter Diettrich');
writeln('Haruyuki Fujimaki');
writeln('Henry Vermaak');
writeln('Hwang Weng Sun');
writeln('Ido Kanner');
writeln('Igor Paliychuk');
writeln('Imad Goubaa');
writeln('James Chandler Jr.');
writeln('Jan Adamec');
writeln('Jan Foster');
writeln('Janusz Tomczak');
writeln('Jarto Tarpio');
writeln('Jason King');
writeln('Jeffrey A. Wormsley');
writeln('Jeroen van Idekinge');
writeln('Jesus Reyes');
writeln('JiXian Yang');
writeln('Jörg Braun - German translation');
writeln('Johannes Muller');
writeln('Jonas Maebe');
writeln('Joost van der Sluis');
writeln('Jose Alonso Cardenas M.');
writeln('José Martínez - Spanish translation');
writeln('Jose Mejuto');
writeln('Jouke Rensma');
writeln('Juan Salvador Pérez García');
writeln('Juha Manninen');
writeln('Júnior Gonçalves');
writeln('Justin Smyth');
writeln('Karl Brandt');
writeln('Keith Bowes');
writeln('Khaled Shagrouni');
writeln('Kostas Michalopoulos');
writeln('Krzysztof Dibowski');
writeln('Ladislav Michl');
writeln('Laurent Jacques');
writeln('Leslie Kaye');
writeln('Louis Hoefler');
writeln('Luca Olivetti');
writeln('Lucas Martin');
writeln('Ludo Brands');
writeln('Luis R. Hilario B.');
writeln('Luís Rodrigues');
writeln('Luiz Américo');
writeln('Maciej Izak (hnb)');
writeln('Marc Fokker');
writeln('Marc Geldon');
writeln('Marc Weustink');
writeln('Marcelo Borges de Paula');
writeln('Marcin Wiązowski');
writeln('Mario Bonati');
writeln('Mario Ray Mahardhika');
writeln('Marius Ellen');
writeln('Mark Bravington');
writeln('Mark Morgan Lloyd');
writeln('Markus Muller');
writeln('Martin Friebe');
writeln('Martin Patik');
writeln('Martin Smat');
writeln('Márton Papp');
writeln('Martyn Ranyard');
writeln('Massimo Magnano');
writeln('Massimo Soricetti');
writeln('Matthijs Willemstein');
writeln('Mattias Gärtner');
writeln('Mattias Hansson');
writeln('Maxim Ganetsky');
writeln('Mazen Neifer');
writeln('Micha Nelissen');
writeln('Michael A. Hess');
writeln('Michael Fuchs');
writeln('Michael W. Vogel');
writeln('Michal Bukovjan');
writeln('Michal Gawrycki');
writeln('Michalis Kamburelis');
writeln('Mike Sapsard');
writeln('Mike Thompson');
writeln('Nikolay Ermolov');
writeln('Nur Cholif Murtadho');
writeln('Olivier Guilbaud');
writeln('Olexandr Pylypchuk - Ukrainian translation');
writeln('Ondrej Pokorny');
writeln('Pascal Riekenberg');
writeln('Patrick Chevalley');
writeln('Paul Ishenin');
writeln('Paul Michell');
writeln('Pawel Trochimczuk');
writeln('Peter Dyson');
writeln('Péter Gábor');
writeln('Petr Kristan');
writeln('Philip J. Hess');
writeln('Philippe Picard');
writeln('Pierre Gillmann');
writeln('Pino Toscano');
writeln('Przemyslaw Nagay');
writeln('Radek Cervinka');
writeln('Raul Moratalla');
writeln('Razvan Adrian Bogdan');
writeln('Reimar Grabowski');
writeln('Reinier Olislagers');
writeln('Roland Hahn - Component icons');
writeln('Roozbeh GHolizadeh');
writeln('Rostislav Okulov');
writeln('Salvatore Coppola');
writeln('Samuel Herzog');
writeln('Samuel Liddicott');
writeln('Sandro Cumerlato');
writeln('Sean McIlwain');
writeln('Sebastian Gasiorek');
writeln('Seppo Suutarla - Finnish translation');
writeln('Sérgio Marcelo');
writeln('Shane Miller');
writeln('Sileno Goedicke');
writeln('Silvio Clécio');
writeln('Simon Ameis');
writeln('Slavko Fedorik');
writeln('Stefan Hille');
writeln('Takeda Matsuki');
writeln('Tamás Kálcza - Hungarian translation');
writeln('Taras Boychuk');
writeln('Theo Lustenberger');
writeln('Tim P. Launchbury');
writeln('Tobias Giesen');
writeln('Tom Lisjac');
writeln('Tomáš Gregorovič');
writeln('Tomasz Wieckowski');
writeln('Tony Maro');
writeln('Vaclav Valicek');
writeln('Valdas Jankūnas');
writeln('Valdinilson Lourenço da Cunha');
writeln('Vasily I. Volchenko');
writeln('Vincent Beuselinck');
writeln('Vincent Snijders');
writeln('Vladimir Serotyukov');
writeln('Vladimir Zhirov');
writeln('Vojtech Cihak');
writeln('Wanderlan Santos dos Anjos');
writeln('Werner Pamler');
writeln('Wojciech Malinowski');
writeln('Yauheni Nazimau');
writeln('Yuichiro Takahashi');
writeln('Yuriy Yeroshkin');
writeln('Yury Sidorov');
writeln('Zaenal Mutaqin');
writeln('Zaher Dirkey');
writeln('Zdravko Gabrovski');
writeln('Zeljan Rikalo');
writeln('Zheng Jian Ping aka - Simplified Chinese translation');
writeln('Žilvinas Ledas');
writeln('Zoë Peterson');
    end;
end.